function [plane] = findTotalWeight(plane)
%weight in pounds (verify this with other functions)
    plane.performance.totalEmptyWeight = plane.empennage.HSweight + ...
        plane.empennage.VSweight + plane.fuselage.weight + plane.fuselage.gearWeight + ...
        plane.power.weight + plane.wing.weight;
    
    plane.performance.totalWeight2 = plane.performance.totalEmptyWeight + ...
        0.042*plane.fuselage.numSyringes; %0.042 pounds per syringe
    
    plane.performance.totalWeight3 = plane.performance.totalEmptyWeight + ...
        0.5*plane.fuselage.numVials; %8 ounces (half a pound) per vial
end